-- Generated from db/lexicon.sqlite on 2026-02-21 20:08:32 UTC
begin;
truncate table public.verbs;
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_backen', 'backen', 'buk', 'gebacken', 'to bake', '굽다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_beginnen', 'beginnen', 'begann', 'begonnen', 'to begin', '시작하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_beissen', 'beißen', 'biss', 'gebissen', 'to bite', '물다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bergen', 'bergen', 'barg', 'geborgen', 'to recover, to salvage', '구조하다, 건져내다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sich_besinnen', 'sich besinnen', 'besann', 'besonnen', 'to reflect, to recollect oneself', '숙고하다, 정신을 차리다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_betruegen', 'betrügen', 'betrog', 'betrogen', 'to deceive, to cheat', '속이다, 사기치다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bewegen', 'bewegen', 'bewog', 'bewogen', 'to move, to motivate', '움직이다, 감동시키다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_beweisen', 'beweisen', 'bewies', 'bewiesen', 'to prove', '증명하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bieten', 'bieten', 'bot', 'geboten', 'to offer', '제공하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_binden', 'binden', 'band', 'gebunden', 'to bind, to tie', '묶다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bitten', 'bitten', 'bat', 'gebeten', 'to ask, to request', '부탁하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bleiben', 'bleiben', 'blieb', 'geblieben', 'to stay, to remain', '머무르다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_braten', 'braten', 'briet', 'gebraten', 'to fry, to roast', '굽다, 볶다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_brechen', 'brechen', 'brach', 'gebrochen', 'to break', '부수다, 깨지다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_brennen', 'brennen', 'brannte', 'gebrannt', 'to burn', '타다, 태우다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_bringen', 'bringen', 'brachte', 'gebracht', 'to bring', '가져오다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_denken', 'denken', 'dachte', 'gedacht', 'to think', '생각하다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_dringen', 'dringen', 'drang', 'gedrungen', 'to penetrate, to urge', '침투하다, 강하게 요구하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_empfehlen', 'empfehlen', 'empfahl', 'empfohlen', 'to recommend', '추천하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_entscheiden', 'entscheiden', 'entschied', 'entschieden', 'to decide', '결정하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_erschrecken', 'erschrecken', 'erschrak', 'erschrocken', 'to be frightened, to frighten', '놀라다, 놀라게 하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_essen', 'essen', 'aß', 'gegessen', 'to eat', '먹다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fahren', 'fahren', 'fuhr', 'gefahren', 'to drive, to go', '가다, 운전하다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fallen', 'fallen', 'fiel', 'gefallen', 'to fall', '떨어지다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fangen', 'fangen', 'fing', 'gefangen', 'to catch', '잡다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_finden', 'finden', 'fand', 'gefunden', 'to find', '찾다, 발견하다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fliegen', 'fliegen', 'flog', 'geflogen', 'to fly', '날다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fliehen', 'fliehen', 'floh', 'geflohen', 'to flee', '도망치다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fliessen', 'fließen', 'floss', 'geflossen', 'to flow', '흐르다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_fressen', 'fressen', 'fraß', 'gefressen', 'to eat (animals)', '(동물이) 먹다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_frieren', 'frieren', 'fror', 'gefroren', 'to freeze, to be cold', '춥다, 얼다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schlagen', 'schlagen', 'schlug', 'geschlagen', 'to hit, to beat', '치다, 때리다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schleichen', 'schleichen', 'schlich', 'geschlichen', 'to sneak, to creep', '살금살금 가다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schleifen', 'schleifen', 'schliff', 'geschliffen', 'to grind, to sharpen', '갈다, 연마하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schliessen', 'schließen', 'schloss', 'geschlossen', 'to close, to shut', '닫다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schlingen', 'schlingen', 'schlang', 'geschlungen', 'to swallow quickly, to wind', '급히 먹다, 휘감다', 'C1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schmeissen', 'schmeißen', 'schmiss', 'geschmissen', 'to throw', '던지다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schmelzen', 'schmelzen', 'schmolz', 'geschmolzen', 'to melt', '녹다, 녹이다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schneiden', 'schneiden', 'schnitt', 'geschnitten', 'to cut', '자르다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schreiben', 'schreiben', 'schrieb', 'geschrieben', 'to write', '쓰다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schreien', 'schreien', 'schrie', 'geschrien', 'to scream, to shout', '소리치다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schreiten', 'schreiten', 'schritt', 'geschritten', 'to stride, to step', '성큼성큼 걷다', 'C1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schweigen', 'schweigen', 'schwieg', 'geschwiegen', 'to be silent', '침묵하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schwellen', 'schwellen', 'schwoll', 'geschwollen', 'to swell', '붓다, 부풀다', 'C1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schwimmen', 'schwimmen', 'schwamm', 'geschwommen', 'to swim', '수영하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schwingen', 'schwingen', 'schwang', 'geschwungen', 'to swing', '흔들다, 휘두르다', 'C1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_schwoeren', 'schwören', 'schwor', 'geschworen', 'to swear', '맹세하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sehen', 'sehen', 'sah', 'gesehen', 'to see', '보다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_senden', 'senden', 'sandte', 'gesandt', 'to send', '보내다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_singen', 'singen', 'sang', 'gesungen', 'to sing', '노래하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sinken', 'sinken', 'sank', 'gesunken', 'to sink', '가라앉다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sitzen', 'sitzen', 'saß', 'gesessen', 'to sit', '앉아 있다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_spinnen', 'spinnen', 'spann', 'gesponnen', 'to spin', '실을 잣다, 헛소리하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sprechen', 'sprechen', 'sprach', 'gesprochen', 'to speak, to talk', '말하다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_springen', 'springen', 'sprang', 'gesprungen', 'to jump', '뛰다, 점프하다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_stechen', 'stechen', 'stach', 'gestochen', 'to sting, to stab', '찌르다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_stehen', 'stehen', 'stand', 'gestanden', 'to stand', '서 있다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_stehlen', 'stehlen', 'stahl', 'gestohlen', 'to steal', '훔치다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_steigen', 'steigen', 'stieg', 'gestiegen', 'to rise, to climb', '오르다, 상승하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sterben', 'sterben', 'starb', 'gestorben', 'to die', '죽다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_stossen', 'stoßen', 'stieß', 'gestoßen', 'to push, to bump', '밀다, 부딪치다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_streichen', 'streichen', 'strich', 'gestrichen', 'to paint, to stroke', '칠하다, 쓰다듬다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_streiten', 'streiten', 'stritt', 'gestritten', 'to argue, to quarrel', '다투다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_tragen', 'tragen', 'trug', 'getragen', 'to carry, to wear', '들다, 입다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_treffen', 'treffen', 'traf', 'getroffen', 'to meet', '만나다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_treiben', 'treiben', 'trieb', 'getrieben', 'to drive, to push', '몰다, 추진하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_treten', 'treten', 'trat', 'getreten', 'to step, to kick', '밟다, 걷어차다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_trinken', 'trinken', 'trank', 'getrunken', 'to drink', '마시다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_tun', 'tun', 'tat', 'getan', 'to do', '하다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_ueberwinden', 'überwinden', 'überwand', 'überwunden', 'to overcome', '극복하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_unterscheiden', 'unterscheiden', 'unterschied', 'unterschieden', 'to distinguish', '구별하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_verderben', 'verderben', 'verdarb', 'verdorben', 'to spoil, to ruin', '망치다, 상하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_vergessen', 'vergessen', 'vergaß', 'vergessen', 'to forget', '잊다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_verlieren', 'verlieren', 'verlor', 'verloren', 'to lose', '잃다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_verschwinden', 'verschwinden', 'verschwand', 'verschwunden', 'to disappear, to vanish', '사라지다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_verzeihen', 'verzeihen', 'verzieh', 'verziehen', 'to forgive', '용서하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_wachsen', 'wachsen', 'wuchs', 'gewachsen', 'to grow', '자라다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_waschen', 'waschen', 'wusch', 'gewaschen', 'to wash', '씻다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_weichen', 'weichen', 'wich', 'gewichen', 'to yield, to give way', '물러나다, 비키다', 'C1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_weisen', 'weisen', 'wies', 'gewiesen', 'to point, to direct', '가리키다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_sich_wenden', 'sich wenden', 'wandte', 'gewandt', 'to turn to, to address', '~에게 의지하다, 방향을 돌리다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_wenden', 'wenden', 'wandte', 'gewandt', 'to turn', '돌리다, 방향을 바꾸다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_werben', 'werben', 'warb', 'geworben', 'to recruit, to advertise', '모집하다, 광고하다', 'B2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_werfen', 'werfen', 'warf', 'geworfen', 'to throw', '던지다', 'A2');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_wiegen', 'wiegen', 'wog', 'gewogen', 'to weigh', '무게가 나가다, 달다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_wissen', 'wissen', 'wusste', 'gewusst', 'to know', '알다', 'A1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_ziehen', 'ziehen', 'zog', 'gezogen', 'to pull, to move', '끌다, 이사하다', 'B1');
insert into public.verbs (id, infinitive, praeteritum, partizip2, english_meaning, korean_meaning, verb_level) values ('verb_zwingen', 'zwingen', 'zwang', 'gezwungen', 'to force', '강요하다', 'B2');
commit;
